version: "3.2"

services:

  # -------------------------------------
  # Firebase Eumulator
  # -------------------------------------
  emulator:
    image: ewestudios/firebase-tools-emulator:latest
    build: .
    volumes:
	  - ./firebase:/app/firebase:rw
    env-file:
	  - .env
	networks:
		- firebase
    ports:
      - 5001:5001
      - 9000:9000
      - 8084:8084
      - 8085:8085
      - 5000:5000
      - 4000:4000

networks:
	firebase:

volumes:
