version: "3.8"

services:

  # -------------------------------------
  # Firebase Eumulator
  # -------------------------------------
  firebase-emulator:
    image: ewestudios/firebase-tools-emulator:latest
    volumes:
      - "./firebase:/app/firebase:rw"
    env_file:
      - .env
    networks:
      - firebase
    ports:
      - 5001:5001
      - 9000:9000
      - 8084:8084
      - 8085:8085
      - 5000:5000
      - 4000:4000
      - 4400:4400
      - 4500:4500

networks:
    firebase:
