setup:
	cd ./firebase/functions && npm install && npm run build && cd -

build-functions:
	cd ./firebase/functions && npm run build && cd -

deploy-functions:
	cd ./firebase/functions && npm run deploy && cd -

function-shell:
	cd ./firebase/functions && npm run shell && cd -

function-serve:
	cd ./firebase/functions && npm run serve && cd -

function-up:
	cd ./firebase/functions && npm run start && cd -

up:
	docker-compose up -d

down:
	docker-compose down

logs:
	docker-compose logs

flogs:
	docker-compose logs -f
