FROM ewestudios/firebase-tools:latest

COPY ./entrypoint-emulator.sh /app/entrypoint.sh

WORKDIR /app/firebase

EXPOSE 4000
EXPOSE 8080
EXPOSE 8084
EXPOSE 9099
EXPOSE 5001
EXPOSE 9000
EXPOSE 8085

CMD ["/app/entrypoint.sh"]
